<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SemanticDesktop.UIA</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SemanticDesktop.Core\SemanticDesktop.Core.csproj" />
    <ProjectReference Include="..\SemanticDesktop.Win32\SemanticDesktop.Win32.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FlaUI.UIA3" Version="4.0.0" />
  </ItemGroup>
</Project>
